#570 - Formik UI values
department-of-veterans-affairs/va-forms-system-core pull request #594
Opened 2022-08-25 19:19 UTC by mlauren

## Description
When the fields are not in schema formik doesn't register the field in initial values. Sometimes, there are data points (previously used in UI schema) that need to be used for the sole purpose of showing and hiding different fields. When these fields are not registered, formik doesn't hook into any validation functions for it. This needs to be added so formik registers it as an initial value. 

## Original issue(s)

department-of-veterans-affairs/va-forms-system-core#570

## Testing done

## Screenshots

## Definition of done

- [ ] Package.json version has been updated to match Github release tag
- [ ] Documentation has been updated, if applicable
- [ ] A link to the original github issue has been provided
- [ ] No sensitive information (i.e. PII/credentials/internal URLs etc.) is captured in logging, hardcoded, or specs

2022-08-31 21:12 UTC, obliviga approved these changes

2022-09-01 15:46 UTC, harshil1793 requested changes
Great work :) Do you mind writing a tsdoc for uiFormData explaining what its for?

2022-09-01 15:46 UTC, bjmccotter7192 reviewed
Left one comment about testing the data and could you add a how-to doc about the usage of the `uiFormData`.

2022-09-01 15:46 UTC, bjmccotter7192 commented on src/routing/FormRouter.tsx
> +  const formValues = { ...initialValues, ...uiInitialValues };
Should we add some tests around this logic to make sure we are getting the correct values?

2022-09-01 22:38 UTC, merged